version: '3.1'

services:
    mysql-observium-db :
        image: mysql-observium-db:1.0
        hostname: mysql-observium-db

    observium-dev:
        image: observium-test:1.0
        ports: 
          - 80:80 # Web
          - 514:514/udp # Syslog
          - 161:161/udp # SNMP
          - 162:162/udp # SNMP Trap
          - 69:69/udp # TFTP
        hostname: observium
