version: '3.1'

services:
    mysql-observium-db :
        image: mysql-observium-db:1.0
        hostname: mysql-observium-db

    observium-dev:
        image: observium-test:1.0
        ports: 
          - 80:80
          - 514:514/udp
          - 161:161/udp
          - 162:162/udp
        hostname: observium
